#!/usr/bin/env bash

export ARTIFACTS="/usr/local/share/cca"
export LINUX_BASE_ADDR="0x84000000"
export INITRD_BASE_ADDR="0x83000000"

screen -dmS FVP -t 'FVP' /opt/fvp/Base_RevC_AEMvA_pkg/models/Linux64*/FVP_Base_RevC-2xAEMvA \
		-f /usr/local/etc/fvp/cca.config \
		-C bp.secureflashloader.fname=$ARTIFACTS/bl1-linux.bin \
		-C bp.flashloader0.fname=$ARTIFACTS/fip-linux.bin \
		--data cluster0.cpu0=$ARTIFACTS/Image@$LINUX_BASE_ADDR \
        --data cluster0.cpu0=$ARTIFACTS/initramfs.cpio@$INITRD_BASE_ADDR \
		-C bp.virtiop9device.root_path=/
sleep 5
screen -r Linux
screen -S FVP -X quit